name: Node.js CI/CD

on:
  push:
    branches: [ master ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'frontend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21.6.2'
        cache: 'yarn'
    - name: Install dependencies (frontend)
      run: |
        cd frontend
        yarn install 
    - name: Run tests (frontend)
      run: |
        cd frontend
        yarn test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21.6.2'
        cache: 'yarn'
    - name: Install dependencies (frontend)
      run: |
        cd frontend
        yarn install 
    - name: Build (frontend)
      run: |
        cd frontend
        yarn build --if-present
    - name: Upload to S3
      uses: aws-actions/amazon-s3-sync@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        SOURCE_DIR: './frontend/build'
        AWS_REGION: 'ap-northeast-2'
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
